update google closure compiler dependency, fix JSSourceFile -> SourceFile
JSSourceFile was renamed, asset minification with v20141120 fails with
java.lang.ClassNotFoundException: com.google.javascript.jscomp.JSSourceFile

this commit updates the closure compiler dependency, bumps the version to
0.1.5-SNAPSHOT, and renames s/JSSourceFile/SourceFile/g